# 1. Pregunta 1

$$A_{,1} \otimes B_{1,} + A_{,2} \otimes B_{2,} + ... + A_{,n} \otimes B_{n,} $$

In [6]:
import numpy as np
np.random.seed(42)

A = np.random.rand(3,3)
B = np.random.rand(3,3)

A.dot(B)

array([[1.19086771, 0.43228703, 0.92025228],
       [0.58238032, 0.09291206, 0.69087197],
       [0.87241658, 0.36800327, 0.52926729]])

In [7]:
result = np.zeros((3,3))
for i in range(3):
    result += np.outer(A[:,i], B[i,])

In [8]:
A.dot(B)

array([[1.19086771, 0.43228703, 0.92025228],
       [0.58238032, 0.09291206, 0.69087197],
       [0.87241658, 0.36800327, 0.52926729]])

In [9]:
result

array([[1.19086771, 0.43228703, 0.92025228],
       [0.58238032, 0.09291206, 0.69087197],
       [0.87241658, 0.36800327, 0.52926729]])

# Pregunta 2

In [10]:
A = np.array([
    [2,4,-2],
    [-2,-3,7],
    [3,9,-4]
])

L2 = np.array([
    [1,0,0],
    [0,1,0],
    [0,-3,1] # a la fila 3 = fila 3 - 3 veces la fila 2. 
])

L1 = np.array([
    [1,0,0],
    [1,1,0], # fila 2 = fila 2 + fila 1
    [-3/2,0,1] # fila 3 = fila 3 - 3/2 fila 1
])

# L2 * L1 * A = U

U = L2 @ L1 @ A
U

array([[  2.,   4.,  -2.],
       [  0.,   1.,   5.],
       [  0.,   0., -16.]])

In [11]:
L = np.linalg.inv(L2 @ L1)
L @ U

array([[ 2.,  4., -2.],
       [-2., -3.,  7.],
       [ 3.,  9., -4.]])

In [12]:
L @ U

array([[ 2.,  4., -2.],
       [-2., -3.,  7.],
       [ 3.,  9., -4.]])

# Pregunta 3

In [13]:
from sklearn.datasets import load_iris

A = load_iris()["data"]
A

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [36]:
k = 2

def pca_eig(A,k):
    A_center = A - A.mean(axis = 0)
    S = 1 / (A.shape[0] - 1) * A_center.T @ A_center
    var, P = np.linalg.eig(S)

    idx = np.argsort(-var)

    var, P = var[idx]/var.sum(), P[:,idx]
    if 1 <= k <= A.shape[1]:
        return P.T[:k], var[:k]
    elif 0 < k < 1:
        idx = np.argmax(var.cumsum() > k) + 1
        return P.T[:idx], var[:idx]
    else:
        raise Exception("K debe ser un número entre 0 y 1, o un entero entre 1 y el número de columnas de A.")

In [37]:
for k in [2,3,0.95,0.98]:
    C, var_exp = pca_eig(A, k)
    print(f"PCA, k = {k}:--------------------")
    print(C)
    print("Var Exp:--------------------------")
    print(var_exp)

PCA, k = 2:--------------------
[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [-0.65658877 -0.73016143  0.17337266  0.07548102]]
Var Exp:--------------------------
[0.92461872 0.05306648]
PCA, k = 3:--------------------
[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [-0.65658877 -0.73016143  0.17337266  0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]]
Var Exp:--------------------------
[0.92461872 0.05306648 0.01710261]
PCA, k = 0.95:--------------------
[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [-0.65658877 -0.73016143  0.17337266  0.07548102]]
Var Exp:--------------------------
[0.92461872 0.05306648]
PCA, k = 0.98:--------------------
[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [-0.65658877 -0.73016143  0.17337266  0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]]
Var Exp:--------------------------
[0.92461872 0.05306648 0.01710261]


In [39]:
from sklearn.decomposition import PCA
for k in [2,3,0.95,0.98]:
    pca = PCA(n_components = k)
    pca.fit(A)
    C, var_exp = pca.components_, pca.explained_variance_ratio_
    print("PCA Sklearn: Iris, k = ", k)
    print("C: -----------------------------------------------------------")
    print(C)
    print("Var Exp: -----------------------------------------------------")
    print(var_exp)
    print("")



PCA Sklearn: Iris, k =  2
C: -----------------------------------------------------------
[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]]
Var Exp: -----------------------------------------------------
[0.92461872 0.05306648]

PCA Sklearn: Iris, k =  3
C: -----------------------------------------------------------
[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]]
Var Exp: -----------------------------------------------------
[0.92461872 0.05306648 0.01710261]

PCA Sklearn: Iris, k =  0.95
C: -----------------------------------------------------------
[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]]
Var Exp: -----------------------------------------------------
[0.92461872 0.05306648]

PCA Sklearn: Iris, k =  0.98
C: -----------------------------------------------------------
[[ 