In [1]:
import numpy as np

a = [1,2,3,4,5]
a_2 = []
for item in a:
    a_2.append(item**2)
a_2
    

[1, 4, 9, 16, 25]

In [2]:
a = np.array([1,2,3,4,5])
a + 2

array([3, 4, 5, 6, 7])

In [3]:
a**2 # Vectorización... 

array([ 1,  4,  9, 16, 25])

In [4]:
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])

a.shape 
# Unidimensional: Vector
# Bidimensional: Matriz
# Tridimensional o más: Tensor...




(6,)

In [5]:
a.reshape(3,2)
b.reshape(-1,3)
a.reshape(4,-1) # Asegurarme que al menos una de las dimensiones esté correcta... sino hay error

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [6]:
# Numpy tiene matrices especiales... Constructores rápidos...

np.random.rand(2,3) # valores aleatorios

array([[0.23262006, 0.4004454 , 0.38539968],
       [0.14409829, 0.59581282, 0.18364471]])

In [7]:
np.random.randint(1,10, (2,2)) # entre 1 y 9... 

array([[8, 1],
       [3, 5]])

In [8]:
np.zeros((2,3)) # matrices de zeros...
np.ones((3,2))
np.empty((3,3)) # Es muy bajo en memoria... y los valores que aparecen son referenciales... 
np.eye(10) # Matriz Identidad

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
# Indexacion... 
A = np.array(
    [
        [1,3,0,6],
        [2,4,1,5],
        [1,4,-2,9]
    ]
)

B = np.array([
    [1,3,-1],
    [2,-1,1],
    [1,-3,-2]
])

print(A.shape)
print(B.shape)

print(A.ndim)
print(B.ndim)

(3, 4)
(3, 3)
2
2


In [10]:
A[:,0].shape # Vectores (n,) son como genéricos..
A[0,:].shape

(4,)

In [11]:
A[:,0].reshape(-1,1).shape

(3, 1)

In [12]:

A[:,0].reshape(1,-1).shape

(1, 3)

In [13]:
B[2,2]

-2

In [14]:
B[:2,2:]

array([[-1],
       [ 1]])

In [15]:
# Operaciones... Suma, Multiplicación por Escalar, Multiplicación Matricial: (Producto Punto/Interno, Producto Externo... )
a + b

array([ 8, 10, 12, 14, 16, 18])

In [16]:
A + A

array([[ 2,  6,  0, 12],
       [ 4,  8,  2, 10],
       [ 2,  8, -4, 18]])

In [17]:
a

array([1, 2, 3, 4, 5, 6])

In [18]:
b_ = b.reshape(-1,1)
b_

array([[ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [19]:
a + b_ # Esto es un error? Sí: Matemáticamente... No: Computacionalmente...
# Broadcasting: Ilegal matemáticamente, pero ultra eficiente Computacionalmente

array([[ 8,  9, 10, 11, 12, 13],
       [ 9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15, 16],
       [12, 13, 14, 15, 16, 17],
       [13, 14, 15, 16, 17, 18]])

In [20]:
a = np.array([
    [0,0,0],
    [10,10,10],
    [20,20,20],
    [30,30,30]
])

b = np.array([1,2,3])

a + b


array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [21]:
a.shape, b.shape # vector genérico... 

# Broadcast:
# Voy a linear los objetos, derecha a izquierda en términos de dimension...
#4,3
#-,3
# Broadcast está permitido si es que las dimensiones son iguales, son 1 o no existen.... dimensión por dimensión...

#4,3,2
#-,2,1
# No pueden hacer broadcast...

a + np.repeat(b.reshape(1,-1), 4, axis = 0)

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [22]:
# Multiplicación...

A.shape, B.shape

# A.dot(B)
B.dot(A) # Producto Matricial

b.dot(b) # Producto Punto... 
B @ A
A @ B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

# Ejercicio: Implementar el Producto Externo tal que:

$$\bar{x}\otimes\bar{y}=\begin{bmatrix}
x_1 y_1 & x_1 y_2 & \cdots & x_1 y_m\\
x_2 y_1 & x_2 y_2 & \cdots & x_2 y_m\\
\vdots & \vdots & \vdots & \vdots\\
x_n y_1 & x_n y_2 & \cdots & x_n y_m\\
\end{bmatrix}$$

In [23]:
x = np.array([4,5,6])
y = np.array([1,2,3])

size_x = len(x) #x.shape[0]
size_y = y.shape[0]

resultado = np.empty((size_x, size_y))
for idx_i, item_i in enumerate(x):
    for idx_j, item_j in enumerate(y):
        resultado[idx_i,idx_j] = item_i*item_j
resultado

array([[ 4.,  8., 12.],
       [ 5., 10., 15.],
       [ 6., 12., 18.]])

In [24]:
x = np.array([4,5,6])
y = np.array([1,2,3])

size_x = len(x) #x.shape[0]
size_y = y.shape[0]
for idx_j, item_j in enumerate(y):
    resultado[:,idx_j] = item_j * x

resultado


array([[ 4.,  8., 12.],
       [ 5., 10., 15.],
       [ 6., 12., 18.]])

In [25]:
x.reshape(-1,1) # vector columna...
y.reshape(1,-1) # Vector fila
# 3,1
# 1,3

x.reshape(-1,1).dot(y.reshape(1,-1))
np.outer(x,y) # Producto Externo...

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])