In [1]:
import numpy as np


def f(x, y):
    return (x - 1) ** 2 + (y - 2) ** 2 + 1


def grad_f(x, y):
    return np.array([2 * (x - 1), 2 * (y - 2)])


def inv_hessian():
    return np.linalg.inv(np.array([[2, 0], [0, 2]]))


def newton_raphson(x_0, num_iter):
    x_t = [x_0]
    for n in range(num_iter):
        x = x_t[n][0]
        y = x_t[n][1]
        x_t.append(x_t[n] - inv_hessian().dot(grad_f(x, y)))

    sol = x_t[-1]
    return sol, x_t


x_0 = np.array([-0.5, 0.5])
sol, x_t = newton_raphson(x_0, num_iter=2)
x, y = sol
f(x, y), x_t

(1.0, [array([-0.5,  0.5]), array([1., 2.]), array([1., 2.])])

In [3]:
import math


def f(x, y):
    return np.array([x**2 + y**2 - 5, x * math.exp(y) + math.exp(2 * x)])


def jacobian(x, y):
    return np.array([[2 * x, 2 * y], [math.exp(y), 0]])


def newton_raphson_eq(x_0, num_iter=10):
    x_t = [x_0]
    for n in range(num_iter):
        x = x_t[n][0]
        y = x_t[n][1]
        inv_jacob = np.linalg.inv(jacobian(x, y))
        x_t.append(x_t[n] - inv_jacob.dot(f(x, y)))

    sol = x_t[-1]
    return sol, x_t


x_0 = np.array([0.5, 0.5])
sol, x_t = newton_raphson_eq(x_0)

In [4]:
sol

array([-0.08951816,  2.23427539])

In [5]:
x_t

[array([0.5, 0.5]),
 array([-1.64872127,  7.14872127]),
 array([-2.90595376e-05,  4.11419047e+00]),
 array([-0.01633821,  2.66474807]),
 array([-0.06737882,  2.270186  ]),
 array([-0.09027058,  2.23464503]),
 array([-0.0893507 ,  2.23428231]),
 array([-0.08954771,  2.23427421]),
 array([-0.08951316,  2.23427559]),
 array([-0.08951922,  2.23427534]),
 array([-0.08951816,  2.23427539])]