In [2]:
import numpy as np

A = np.array([
    [8,3],
    [2,7]
])
eig_values, eig_vectors = np.linalg.eig(A)
eig_vectors # Vectores se entregan como columnas...

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [4]:
v1 = np.array([1.5,1])
v2 = np.array([-1,1])

v1/np.linalg.norm(v1)
v2/np.linalg.norm(v2)

array([-0.70710678,  0.70710678])

In [8]:
from sklearn.datasets import load_iris
import numpy as np
np.random.seed(42)

A = load_iris()["data"]
A

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [37]:
# PCA es que vamos a calcular los valores y vectores propios de una matriz de covarianza generada con datos centrados...


def pca_eig(A, k):
    A_center = A - A.mean(axis=0) # Broadcasting... A.mean(axis = 0) (1x4) A 150x4
    n = A_center.shape[0]
    S = 1/(n-1) * A_center.T @ A_center # 150x4

    # PCA
    # valores propios representan la varianza explicada de cada componente. 
    # Vectores propios representan las componentes principales. 

    var, C = np.linalg.eig(S)

    # Ordenamos los valores y vectores de mayor a menor...
    idx = np.argsort(-var)
    var = var[idx]/var.sum()
    C = C[:,idx] # columnas son los CP

    if 1 <= k <= A_center.shape[1]:
        return C.T[:k], var[:k]
    elif 0 < k < 1:
        idx = np.argmax(var.cumsum() > k) + 1
        return C.T[:idx], var[:idx]


In [35]:
from sklearn.decomposition import PCA

for k in [2,3,0.95,0.98]:
    pca = PCA(n_components=k)
    pca.fit(A)
    C = pca.components_
    var_exp = pca.explained_variance_ratio_
    print("---------------------------------")
    print(f"PCA SKlearn: Iris, k = {k}")
    print("---------------------------------")
    print(f"C = {C}")
    print("---------------------------------")
    print(f"Var Explicada = {var_exp}")

---------------------------------
PCA SKlearn: Iris, k = 2
---------------------------------
C = [[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]]
---------------------------------
Var Explicada = [0.92461872 0.05306648]
---------------------------------
PCA SKlearn: Iris, k = 3
---------------------------------
C = [[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]]
---------------------------------
Var Explicada = [0.92461872 0.05306648 0.01710261]
---------------------------------
PCA SKlearn: Iris, k = 0.95
---------------------------------
C = [[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]]
---------------------------------
Var Explicada = [0.92461872 0.05306648]
---------------------------------
PCA SKlearn: Iris, k = 0.98
---------------------------------
C = [[ 0.36138659

In [38]:
for k in [2,3,0.95,0.98]:
    C, var_exp = pca_eig(A, k)
    print("---------------------------------")
    print(f"Nuestra Implementación: Iris, k = {k}")
    print("---------------------------------")
    print(f"C = {C}")
    print("---------------------------------")
    print(f"Var Explicada = {var_exp}")

---------------------------------
Nuestra Implementación: Iris, k = 2
---------------------------------
C = [[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [-0.65658877 -0.73016143  0.17337266  0.07548102]]
---------------------------------
Var Explicada = [0.92461872 0.05306648]
---------------------------------
Nuestra Implementación: Iris, k = 3
---------------------------------
C = [[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [-0.65658877 -0.73016143  0.17337266  0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]]
---------------------------------
Var Explicada = [0.92461872 0.05306648 0.01710261]
---------------------------------
Nuestra Implementación: Iris, k = 0.95
---------------------------------
C = [[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [-0.65658877 -0.73016143  0.17337266  0.07548102]]
---------------------------------
Var Explicada = [0.92461872 0.05306648]
---------------------------------
Nuestra Implementación: Iris, k = 0.98
-------