# Dimensión del Espacio Columna de A? m
$$AB = A_{,1} \otimes B_{1,} + A_{,2} \otimes B_{2,} + ... + A_{,m} \otimes B_{m,} $$

In [4]:
import numpy as np
np.random.seed(42)
A = np.random.rand(3,3)       
B = np.random.rand(3,3)

A @ B

array([[1.19086771, 0.43228703, 0.92025228],
       [0.58238032, 0.09291206, 0.69087197],
       [0.87241658, 0.36800327, 0.52926729]])

In [5]:
result = np.zeros((3,3))
for i in range(A.shape[1]):
    result += np.outer(A[:,i],B[i,:])
    
result
    

array([[1.19086771, 0.43228703, 0.92025228],
       [0.58238032, 0.09291206, 0.69087197],
       [0.87241658, 0.36800327, 0.52926729]])

In [9]:
A = np.array([
    [2,4,-2],
    [-2,-3,7],
    [3,9,-4]
])

# fila 2 = fila 1 + fila 2
# fila 3 = fila 3 - 3/2 fila 1

L1 = np.array([
    [1,0,0],
    [1,1,0], # voy a a sumar la fila 1 y la fila 2 y la guardo en la fila 2
    [-3/2,0,1]
])

L2 = np.array([
    [1,0,0],
    [0,1,0],
    [0,-3,1]
])

U = L2 @ L1 @ A # manera matricial de hacer Gauss... 
U



array([[  2.,   4.,  -2.],
       [  0.,   1.,   5.],
       [  0.,   0., -16.]])

$$L2 \cdot L1 \cdot A = U$$
$$ A = (L2 \cdot L1)^{-1} U$$

In [13]:
## La Multiplicación de dos Triangulares inferiores son Triangular Inferior. 
## La inversa de una Triangular Inferior también es Triangular Inferior

L = L2 @ L1
np.linalg.inv(L) @ U

array([[ 2.,  4., -2.],
       [-2., -3.,  7.],
       [ 3.,  9., -4.]])