In [1]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import pandas as pd
import numpy as np

df = pd.DataFrame(
    dict(
        curvatura=[2.95, 2.53, 3.57, 3.16, 2.58, 2.16, 3.27],
        diametro=[6.63, 7.79, 5.65, 5.47, 4.46, 6.22, 3.52],
        resultado=["Pasa", "Pasa", "Pasa", "Pasa", "No Pasa", "No Pasa", "No Pasa"],
    )
)
df

curvatura  diametro resultado
0       2.95      6.63      Pasa
1       2.53      7.79      Pasa
2       3.57      5.65      Pasa
3       3.16      5.47      Pasa
4       2.58      4.46   No Pasa
5       2.16      6.22   No Pasa
6       3.27      3.52   No Pasa

In [2]:
lda = LinearDiscriminantAnalysis()
lda.fit(df[["curvatura", "diametro"]], df["resultado"])
X = pd.DataFrame(dict(curvatura=[2], diametro=[5]))
lda.predict(X)

array(['No Pasa'], dtype='<U7')

In [3]:
data_1 = df.query("resultado == 'Pasa'")[["curvatura", "diametro"]]
data_2 = df.query("resultado == 'No Pasa'")[["curvatura", "diametro"]]
mu_1 = data_1.mean().values
mu_2 = data_2.mean().values
mu_1, mu_2

(array([3.0525, 6.385 ]), array([2.67      , 4.73333333]))

In [4]:
s1 = data_1.cov().values
s2 = data_2.cov().values
s1, s2

(array([[ 0.187625  , -0.41265   ],
        [-0.41265   ,  1.13716667]]),
 array([[ 0.3141    , -0.7308    ],
        [-0.7308    ,  1.87853333]]))

In [5]:
n1 = len(data_1)
n2 = len(data_2)
s = ((n1 - 1) * s1 + (n2 - 1) * s2) / (n1 + n2 - 2)
inv_s = np.linalg.inv(s)
s, inv_s

(array([[ 0.238215  , -0.53991   ],
        [-0.53991   ,  1.43371333]]),
 array([[28.65752288, 10.7918946 ],
        [10.7918946 ,  4.76151798]]))

In [6]:
beta = (mu_1 - mu_2).dot(inv_s)
beta, lda.coef_

(array([28.78611508, 11.99234021]), array([[28.78611508, 11.99234021]]))

In [15]:
mu_c = (mu_1 + mu_2) / 2
x = X.values.reshape(-1)
decision = beta.dot(x - mu_c)
print(decision)
if decision > 0:
    print("Pasa")
else:
    print("No Pasa")

-31.49775851330466
No Pasa


In [8]:
lda.coef_, lda.intercept_

(array([[28.78611508, 11.99234021]]), array([-148.74400766]))

In [20]:
beta, -beta.dot(mu_c)

(array([28.78611508, 11.99234021]), -149.03168972824614)