# Ayudantía Número 1

# Introducción a Matrices 

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([7, 8, 9, 10, 11, 12])

# Definir Vectores y Matrices

In [3]:
## Matrices: Mencionar también np.empty, np.rand, y las otras matrices especiales. 

A = np.array(
    [
        [1, 3, 0, 6],
        [2, 4, 1, 5],
        [1, 4, -2, 9],
    ]
)

B = np.array(
    [
        [1, 3, -1],
        [2, -1, 1],
        [1, -3, -2],
    ]
)


## Imprimir la forma

print(a.shape)
print(b.shape)
print(A.shape)
print(B.shape)

print(a.ndim)
print(A.ndim)

(6,)
(6,)
(3, 4)
(3, 3)
1
2


# Indexación

In [4]:
## Indexing

print(a[0])
print("--------")
print(b[2])
print("--------")
print(A[:, 1])
print("--------")
print(B[2, :])
print("--------")
print(A[1, 3])
print("--------")

1
--------
9
--------
[3 4 4]
--------
[ 1 -3 -2]
--------
5
--------


In [5]:
## Matrices Especiales: Improvisar ejercicios cambiando elementos utilizando Indexación.

print(np.eye(5))
print("-------")
print(np.ones((5, 3)))
print("-------")
print(np.zeros((5, 3)))
print("-------")

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------


# Reshaping

In [6]:
## Reshaping
c = a.reshape(3, 2)
d = b.reshape(3, 2)

print(c.shape)
print(d.shape)
print("--------")
print(A.T)
print("--------")
print(B.T)

(3, 2)
(3, 2)
--------
[[ 1  2  1]
 [ 3  4  4]
 [ 0  1 -2]
 [ 6  5  9]]
--------
[[ 1  2  1]
 [ 3 -1 -3]
 [-1  1 -2]]


In [7]:
## Ojo con ciertas formas
a_ = a.reshape(6, -1)
b_ = b.reshape(6, -1)
print(a_)
print(b_)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


# Propiedades de Suma y Multiplicación por Escalar

In [8]:
# Posibles problemas con la Suma...
print(a_.ndim)
print(b_.ndim)

2
2


In [9]:
a + b

array([ 8, 10, 12, 14, 16, 18])

In [10]:
c + d

array([[ 8, 10],
       [12, 14],
       [16, 18]])

# Ejercicio Bonus: Implementar el Producto Punto, utilizando Numpy

In [11]:
# Producto Punto sin Optimizar: Validar si las formas son incorrectas...
result = []
for i in range(len(a)):
    result.append(a[i] * b[i])
sum(result)

# Producto Punto Optimizado
sum([i * j for i, j in zip(a, b)])

217

In [12]:
a.dot(b)

217

In [13]:
print(B.dot(A))
print("--------")
print(B @ A)

[[  6  11   5  12]
 [  1   6  -3  16]
 [ -7 -17   1 -27]]
--------
[[  6  11   5  12]
 [  1   6  -3  16]
 [ -7 -17   1 -27]]


# Problemas con la Suma

In [14]:
a_ + b  # Esto es raro

array([[ 8,  9, 10, 11, 12, 13],
       [ 9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15, 16],
       [12, 13, 14, 15, 16, 17],
       [13, 14, 15, 16, 17, 18]])

In [15]:
# Broadcasting...
# La última dimensión es igual a 1 o Son iguales o no existen.
# Sólo no se puede hacer broadcast si dos dimensiones son distintas.

a = np.array(
    [
        [
            0,
            0,
            0,
        ],
        [
            10,
            10,
            10,
        ],
        [
            20,
            20,
            20,
        ],
        [
            30,
            30,
            30,
        ],
    ]
)
b = np.array([1, 2, 3])

a + b


print(a.shape)
print(b.shape)  # (0,3)

b_ = np.repeat(b.reshape(-1, 3), 4, axis=0)
## Axis 0 means rows, Axis 1 means columns
a + b_

(4, 3)
(3,)


array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

# Ejercicio: Implementar el Producto Externo tal que:

$$\bar{x}\otimes\bar{y}=\begin{bmatrix}
x_1 y_1 & x_1 y_2 & \cdots & x_1 y_m\\
x_2 y_1 & x_2 y_2 & \cdots & x_2 y_m\\
\vdots & \vdots & \vdots & \vdots\\
x_n y_1 & x_n y_2 & \cdots & x_n y_m\\
\end{bmatrix}$$

In [16]:
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])

size_x = len(x)
size_y = len(y)
resultado = np.empty((size_x, size_y))
for idx_x, item_x in enumerate(x):
    for idx_y, item_y in enumerate(y):
        resultado[idx_x, idx_y] = item_x * item_y

resultado

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]])

In [17]:
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])

size_x = len(x)
size_y = len(y)

resultado = np.empty((size_x, size_y))
for idx_y, item_y in enumerate(y):
    resultado[:, idx_y] = item_y * x

resultado

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]])

In [18]:
# Explicar el reshape -1
x.reshape(3, 1)
y.reshape(1, 3)

array([[1, 2, 3]])

In [19]:
x.reshape(3, 1).dot(y.reshape(1, 3))

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [20]:
np.outer(x, y)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [33]:
x = np.random.rand(8)
y = np.random.rand(5)
np.outer(x,y)

array([[0.63122346, 0.19493571, 0.60998176, 0.38897759, 0.13498859],
       [0.47399184, 0.14637912, 0.45804123, 0.29208706, 0.10136424],
       [0.07609081, 0.02349852, 0.07353023, 0.04688929, 0.01627219],
       [0.17132824, 0.05290993, 0.16556276, 0.10557726, 0.03663894],
       [0.51388399, 0.15869869, 0.49659095, 0.31666972, 0.10989527],
       [0.65958139, 0.20369326, 0.6373854 , 0.40645254, 0.141053  ],
       [0.73273677, 0.22628525, 0.70807897, 0.45153294, 0.15669744],
       [0.54953002, 0.16970697, 0.53103743, 0.3386358 , 0.11751826]])

## Otras operaciones

In [21]:
# Transpuesta
A.T

array([[ 1,  2,  1],
       [ 3,  4,  4],
       [ 0,  1, -2],
       [ 6,  5,  9]])

In [22]:
# Traza
np.trace(A)

3

In [23]:
# Determinante
print(np.linalg.det(B))

25.000000000000007


In [24]:
# Other example of floating point errors
1.2 - 1.0

0.19999999999999996

In [25]:
# Valores y Vectores Propios
a = np.array([[1 + 1e-9, 0], [0, 1 - 1e-9]])
eig_vals, eig_vecs = np.linalg.eig(a)
print(eig_vals)
print("--------")
print(eig_vecs)  # columns are the ith eigen vector for the ith eigen value...

[1. 1.]
--------
[[1. 0.]
 [0. 1.]]


In [26]:
np.linalg.inv(B)

array([[ 0.2 ,  0.36,  0.08],
       [ 0.2 , -0.04, -0.12],
       [-0.2 ,  0.24, -0.28]])

In [27]:
np.linalg.pinv(B)

array([[ 0.2 ,  0.36,  0.08],
       [ 0.2 , -0.04, -0.12],
       [-0.2 ,  0.24, -0.28]])

In [28]:
# Rango de una Matriz

np.linalg.matrix_rank(np.eye(5))

5

In [29]:
np.linalg.matrix_rank(np.ones(5))

1